version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: react-native-calendars
    versions:
    - 1.1195.0
    - 1.1222.0
    - 1.1230.0
    - 1.1247.0
    - 1.1248.0
    - 1.1249.0
    - 1.1257.0
    - 1.1258.0
    - 1.1259.0
  - dependency-name: detox
    versions:
    - 18.10.0
    - 18.11.1
    - 18.11.2
    - 18.12.0
    - 18.12.1
    - 18.7.0
    - 18.8.1
  - dependency-name: "@react-native-community/masked-view"
    versions:
    - 0.1.11
  - dependency-name: "@sentry/react-native"
    versions:
    - 2.2.2
    - 2.3.0
    - 2.4.1
    - 2.4.2
  - dependency-name: "@babel/runtime"
    versions:
    - 7.12.13
    - 7.12.18
    - 7.12.5
    - 7.13.10
    - 7.13.2
    - 7.13.6
    - 7.13.7
    - 7.13.8
    - 7.13.9
  - dependency-name: react-native-modal
    versions:
    - 11.10.0
    - 11.9.0
  - dependency-name: react-native-camera
    versions:
    - 3.43.3
    - 3.43.5
    - 3.43.6
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: libphonenumber-js
    versions:
    - 1.9.13
    - 1.9.14
    - 1.9.15
    - 1.9.16
    - 1.9.8
    - 1.9.9
  - dependency-name: "@react-native-picker/picker"
    versions:
    - 1.12.0
    - 1.14.0
    - 1.9.12
  - dependency-name: "@react-navigation/bottom-tabs"
    versions:
    - 5.11.8
    - 5.11.9
  - dependency-name: "@react-navigation/compat"
    versions:
    - 5.3.15
  - dependency-name: "@react-navigation/drawer"
    versions:
    - 5.12.5
  - dependency-name: "@react-native-community/datetimepicker"
    versions:
    - 3.2.0
    - 3.3.0
    - 3.4.0
    - 3.4.1
    - 3.4.2
    - 3.4.3
    - 3.4.6
  - dependency-name: google-libphonenumber
    versions:
    - 3.2.18
    - 3.2.19
  - dependency-name: react-i18next
    versions:
    - 11.8.11
  - dependency-name: react-native-reanimated
    versions:
    - 1.13.3
  - dependency-name: qs
    versions:
    - 6.10.0
    - 6.10.1
  - dependency-name: slugify
    versions:
    - 1.4.7
    - 1.5.0
  - dependency-name: ajv-cli
    versions:
    - 4.2.0
  - dependency-name: i18next
    versions:
    - 19.8.6
    - 19.8.7
    - 19.9.1
    - 19.9.2
  - dependency-name: react-native-safe-area-context
    versions:
    - 3.2.0
  - dependency-name: react-native-map-link
    versions:
    - 2.7.22
  - dependency-name: react-native-screens
    versions:
    - 2.18.1
  - dependency-name: react-navigation-stack
    versions:
    - 2.10.4
  - dependency-name: "@react-navigation/material-top-tabs"
    versions:
    - 5.3.14
  - dependency-name: react-navigation-tabs
    versions:
    - 2.11.0
  - dependency-name: "@react-navigation/native"
    versions:
    - 5.9.3
  - dependency-name: "@react-native-firebase/perf"
    versions:
    - 10.6.3
    - 10.6.4
    - 10.7.0
    - 10.8.0
  - dependency-name: "@react-native-firebase/crashlytics"
    versions:
    - 10.6.3
    - 10.6.4
    - 10.7.0
    - 10.8.0
  - dependency-name: countly-sdk-react-native-bridge
    versions:
    - 20.11.3
    - 20.11.4
    - 20.11.5
  - dependency-name: "@react-native-firebase/app"
    versions:
    - 10.6.3
    - 10.6.4
    - 10.7.0
    - 10.8.0
  - dependency-name: "@react-native-firebase/analytics"
    versions:
    - 10.6.4
    - 10.7.0
    - 10.8.0
  - dependency-name: buffer
    versions:
    - 5.7.1
  - dependency-name: "@react-native-community/push-notification-ios"
    versions:
    - 1.8.0
  - dependency-name: native-base
    versions:
    - 2.15.2
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: react-navigation-drawer
    versions:
    - 2.7.1
  - dependency-name: react-redux
    versions:
    - 7.2.4
  - dependency-name: redux
    versions:
    - 4.1.0
