env:
  global:
    - NODE_OPTIONS=--max-old-space-size=8192
    - COUNTLY_SERVER_URL=
    - COUNTLY_APP_KEY=
    - COUNTLY_SALT=

matrix:
  include:
  - language: node_js
    env: LANE='node'
    node_js: 12
    cache: yarn
    script:
      - yarn lint
      - yarn test

notifications:
  email: false
