matrix:
  include:
  - language: node_js
    env: LANE='node'
    node_js: 8
    cache: yarn
  - language: android
    env: ANDROID_API_LEVEL=18
    sudo: required
    jdk: openjdk8
    before_cache:
      - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
      - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
        - "$HOME/.cache/yarn"
        - "$HOME/.gradle/caches/"
        - "$HOME/.gradle/wrapper/"
    android:
      components:
        - tools
        - platform-tools
        - build-tools-28.0.3
        - android-$ANDROID_API_LEVEL
        - extra-google-google_play_services
    before_install:
      - yes | sdkmanager "platforms;android-28"
      - nvm install 8
    before_script:
      - npm install -g yarn
      - yarn config set cache-folder "$HOME/.cache/yarn"
      - yarn install
      - cp google-services.json.dist android/app/google-services.json
    script:
      - cd android && ./gradlew clean && ./gradlew assembleDebug --stacktrace
  - language: android
    env: ANDROID_API_LEVEL=28
    sudo: required
    jdk: openjdk8
    before_cache:
      - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
      - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
        - "$HOME/.cache/yarn"
        - "$HOME/.gradle/caches/"
        - "$HOME/.gradle/wrapper/"
    android:
      components:
        - tools
        - platform-tools
        - build-tools-28.0.3
        - android-$ANDROID_API_LEVEL
        - extra-google-google_play_services
    before_install:
      - nvm install 8
    before_script:
      - npm install -g yarn
      - yarn config set cache-folder "$HOME/.cache/yarn"
      - yarn install
      - cp google-services.json.dist android/app/google-services.json
    script:
      - cd android && ./gradlew clean && ./gradlew assembleDebug --stacktrace
  - language: objective-c
    env: LANE='ios'
    os: osx
    osx_image: xcode10.2
    xcode_workspace: ios/CoopCycle.xcworkspace
    xcode_scheme: CoopCycle
    # cache:
    #   directories:
    #     - "$HOME/.cache/yarn"
    before_install:
      - nvm install 8
      # - gem install xcpretty
      - npm install -g yarn
      # - yarn config set cache-folder "$HOME/.cache/yarn"
      - yarn install
      # - cd ios
    # script:
    #   - xcodebuild -workspace CoopCycle.xcworkspace -scheme CoopCycle -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty && exit ${PIPESTATUS[0]}

notifications:
  email: false

