name: Deploy
on: [workflow_dispatch]
jobs:
  FASTLANE_ANDROID:
    name: Fastlane Deploy Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
      - run: cp .env.dist .env
      - name: Decode sentry.properties file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileDir: "./android/"
          fileName: "sentry.properties"
          encodedString: ${{ secrets.SENTRY_PROPERTIES_BASE64 }}
      - name: Decode google-services.json file
        uses: timheuer/base64-to-file@v1.1
        with:
          fileDir: "./android/app/"
          fileName: "google-services.json"
          encodedString: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
      - run: ls -la android/sentry.properties
      - name: Install RubyGems
        run: |
          cd android/
          bundle install
          cd ..
      - run: yarn install
      - name: Run Fastlane
        run: |
          cd android/
          bundle exec fastlane deploy
          cd ..
